[package]
name = "fledgingr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
extendr-api = "0.3"
sudachi = { git = "https://github.com/WorksApplications/sudachi.rs/" }
